name: Chris Knights
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64816
title: Chris Knights
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-11988923-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d0d0d2'
    - '#393939'
    - '#958c87'
    - '#5b5c60'
  brandStrength: 1
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0
purpose: []
