name: Chris Knights
favicon: null
layout_spectrum: 0
typography_spectrum: 0.21308
title: Chris Knights
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-11988923-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#efabc6'
    - '#c5859d'
    - '#a6677a'
    - '#653c44'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
